name: 'Call REST API when a file is pushed'

on:
  push:
    branches: [ main ] # match specific branch

jobs:
  prepare-files:
    runs-on: ubuntu-latest
    steps:
      - name: Make an API call
        uses: fjogeleit/http-request-action@v1
        with:
          url: 'https://postman-echo.com/post'
          method: 'POST'
