name: 'Call REST API when a file is pushed'

on:
  push:
    branches: [ master ] # match specific branch

jobs:
  prepare-files:
    runs-on: ubuntu-latest
    steps:
      - name: Make an API call
        uses: fjogeleit/http-request-action@v1
        with:
          url: 'andrew-pinner.asuscomm.com/weather?loc=28105'
          method: 'GET'
          timeout: 20000
