name: 'Call REST API when a file is pushed'

on:
  push:
    branches: [ master ] # match specific branch

jobs:
  prepare-files:
    runs-on: ubuntu-latest
    steps:
      - name: Make an API call
        id: deployRequest
        uses: fjogeleit/http-request-action@v1
        with:
          url: 'https://andrew-pinner.asuscomm.com/weather/deploy'
          method: 'POST'
          data: '${{ secrets.DEPLOY_PASSWORD}}'
      - name: Show Response
        run: |
          echo ${{ steps.deployRequest.outputs.response }}
